Use 2.17.0-rc0 [RFC]
TileDB-Inc/TileDB-Py pull request #1823
Opened 2023-09-06 16:03 UTC by johnkerl

This is what I've been using in my sandbox for testing -- food for thought whether we do a `TileDB-Py` RC -- ? cc @nguyenv @ihnorton 

[sc-33703]

2023-09-06 17:22 UTC, johnkerl commented
This is supposed to be _only_ the following atop #1790:

```diff
diff --git a/misc/azure-release.yml b/misc/azure-release.yml
index 662cd86..9ad8985 100644
--- a/misc/azure-release.yml
+++ b/misc/azure-release.yml
@@ -7,7 +7,7 @@ stages:
         LIBTILEDB_SHA: dev
       ${{ else }}:
         TILEDBPY_VERSION: 0.22.3
-        LIBTILEDB_VERSION: 2.16.3
+        LIBTILEDB_VERSION: 2.17.0-rc0
         LIBTILEDB_SHA: 194b5ae2941d7b6631fba367a7afdd79350332e7
       LIBTILEDB_REPO: https://github.com/TileDB-Inc/TileDB
       TILEDB_SRC: "$(Build.Repository.Localpath)/tiledb_src"
diff --git a/setup.py b/setup.py
index 7930eef..cdd3095 100644
--- a/setup.py
+++ b/setup.py
@@ -24,7 +24,7 @@ from setuptools import Extension, find_packages, setup
 # - this is for builds-from-source
 # - release builds are controlled by `misc/azure-release.yml`
 # - this should be set to the current core release, not `dev`
-TILEDB_VERSION = "dev"
+TILEDB_VERSION = "2.17.0-rc0"

 # allow overriding w/ environment variable
 TILEDB_VERSION = os.environ.get("TILEDB_VERSION") or TILEDB_VERSION
```

However, #1790 needs a rebase to today's `dev` here on GitHub, whereas I put up this PR on a locally-rebased #1790 -- hence the unseemly file/line count on this PR as you see here.

2023-09-06 20:25 UTC, ihnorton commented
Kicked off wheel build here: https://github.com/TileDB-Inc/TileDB-Py/pull/new/release-test-2.17.0-rc0

2023-09-08 15:58 UTC, nguyenv requested changes

2023-09-08 15:58 UTC, nguyenv commented on setup.py
> +        "-DTILEDB_VCPK=ON",
Typoed -DTILEDB_VCPKG=ON

2023-09-11 14:49 UTC, nguyenv approved these changes

2023-09-13 02:43 UTC, merged