Correct Nullable String Attributes
TileDB-Inc/TileDB-Py pull request #1848
Opened 2023-10-25 00:06 UTC by nguyenv

* `np.nan_to_num` cannot be used on string arrays

2023-10-25 14:10 UTC, johnkerl commented
@nguyenv in the application-level use case I have this:

```
anndata = ...
anndata.obs['new_col'] = pd.Series(data=np.nan, dtype=np.dtype(str))
if ...:
    anndata.obs['new_col'][10] = 'abc'

# Initial
soma_uri = tiledbsoma.io.from_anndata(
    experiment_uri=soma_uri,
    anndata=anndata,
    measurement_name='RNA'
)

# Update
anndata.obs['new_col'] = 'abc'

# saving updated obs
with tiledbsoma.open(soma_uri, 'w') as soma_exp:
    tiledbsoma.io.update_obs(soma_exp, anndata.obs)
```

When that first `if` is `True` -- the `new_col` column is nine NaNs and one `"abc"` on initial write -- all is well

When that first `if` is `False` -- the `new_col` column is all NaNs on initial write -- I still get

```
Traceback (most recent call last):
  File "/Users/johnkerl/./doronanx.py", line 279, in <module>
    tiledbsoma.io.update_obs(soma_exp, anndata.obs)
  File "/Users/johnkerl/git/single-cell-data/TileDB-SOMA/apis/python/src/tiledbsoma/io/ingest.py", line 1408, in update_obs
    _update_dataframe(
  File "/Users/johnkerl/git/single-cell-data/TileDB-SOMA/apis/python/src/tiledbsoma/io/ingest.py", line 1529, in _update_dataframe
    raise ValueError(f"unsupported type updates: {msg}")
ValueError: unsupported type updates: new_col type double != string
```

and I'm still unsure how to solve this at the `tiledbsoma` level (in an experimental branch).

I'm debating whether to accept this PR, with the caveat that we will need another, or, to request changes on this PR ...

2023-10-25 14:19 UTC, johnkerl requested changes
As discussed

2023-10-26 15:30 UTC, nguyenv commented
I've now corrected the two issues mentioned. 

I do not think these changes will make it into the current release though.

2023-10-26 16:52 UTC, nguyenv commented
Thanks for providing the full script. I was able to repro the issue.

2023-10-26 22:36 UTC, nguyenv commented
This seems to be a problem residing in TileDB-SOMA's `df_to_arrow` converter. It's actually once again an issue where a column with all `pd.NA` is always [inferred](https://github.com/single-cell-data/TileDB-SOMA/blob/bd13a68667a84b068f4ca27152c527f27652e810/apis/python/src/tiledbsoma/_arrow_types.py#L200) as type `double`, so we not be using `pa.infer_type` there and instead specify an explicit type. There doesn't seem to be a convenient Pandas to Pyarrow dtype converter available (only the other way around), so I think I'll add a dtype mapping in `_arrow_types.py` and open a PR in TileDB-SOMA.

2023-10-26 23:03 UTC, johnkerl commented
Ok @nguyenv I'll triple check

I should have mentioned I did this on a soma branch with attempts to handle that

Let me put up the branch for your reference ...

2023-10-26 23:03 UTC, johnkerl approved these changes

2023-10-26 23:06 UTC, nguyenv commented
I haven't done what I think should be the corrections yet, so I can't say with 100% confidence that the problem is only residing in SOMA. I'm going to make sure we can get the repro script to work before I merge this PR.

2023-10-27 13:47 UTC, johnkerl commented
@nguyenv https://github.com/single-cell-data/TileDB-SOMA/pull/1834

2023-11-02 22:44 UTC, johnkerl commented
@nguyenv https://github.com/single-cell-data/TileDB-SOMA/pull/1834 passes with this PR installed locally

2023-11-03 14:53 UTC, nguyenv commented
I've confirmed both this PR and the PR put forth in TileDB-SOMA are working.

2023-11-03 14:53 UTC, merged