Return empty result for invalid enumeration
TileDB-Inc/TileDB-Py pull request #1882
Opened 2023-12-15 21:29 UTC by nguyenv

https://github.com/TileDB-Inc/TileDB-Py/issues/1880

Note that we already supported comparison operators on ordered enumerated values.

2023-12-15 21:32 UTC, nguyenv commented
This is also needs to be ported over to TileDB-SOMA-Py.

2023-12-22 04:35 UTC, ihnorton requested changes
I don't think this is the right way to solve this issue. Let's see if we can address this in libtiledb.

2024-03-14 15:59 UTC, nguyenv commented
[sc-43002]

After discussing with @kounelisagis, we are just going to use this pre-existing PR to add the unit tests instead of opening a new one.

2024-03-15 10:00 UTC, kounelisagis commented
Error comes from libtiledb. Should we address it there?

`FAILED tiledb/tests/test_query_condition.py::QueryConditionTest::test_qc_enumeration - tiledb.cc.TileDBError: TileDB internal: Enumeration value not found for field 'attr2'`

2024-03-15 12:14 UTC, nguyenv commented
We need to wait for the libtiledb 2.21.0 release for this fix and then we can update `setup.py`. Although in the meantime we can test this against 2.21.0-rc2 to make sure CI is all passing.

2024-03-15 17:31 UTC, nguyenv commented on setup.py
> +TILEDB_VERSION = "2.21.0-rc1"
Reminder to revert before merging.

2024-03-15 17:33 UTC, nguyenv commented
@kounelisagis I'm so sorry, when I merged main into this branch I accidentally removed your changes. Can you push your changes again.

2024-03-20 02:46 UTC, ihnorton reviewed
LGTM but please double-check that these all _fail_ without 2.21.

2024-03-21 09:37 UTC, kounelisagis commented
It fails without 2.21 (or at least with 2.20...)

---

```
git checkout viviannguyen/sc-38443/dataframe-value-filter-on-enum-dict-column
pip install -r requirements_dev.txt
python setup.py develop
python -c "import tiledb; print(tiledb.libtiledb.version())"
```
**(2, 21, 0)**
```
pytest -o log_cli=true --log-cli-level=10 tiledb/tests/test_query_condition.py
```
Passes

---

```
git checkout dev setup.py
python setup.py develop
python -c "import tiledb; print(tiledb.libtiledb.version())"
```
**(2, 20, 1)**

```
pytest -o log_cli=true --log-cli-level=10 tiledb/tests/test_query_condition.py
```
Gives the following error:
https://gist.github.com/kounelisagis/7c9d8803b24f92335b2c71d58bc7f9c8

2024-03-21 09:42 UTC, kounelisagis commented
Also tested it with 2.21.0 (not pre-release) and it works.

2024-03-21 09:43 UTC, kounelisagis approved these changes

2024-03-21 15:53 UTC, nguyenv commented
Thanks for doing the work of double checking @kounelisagis.

2024-03-21 15:54 UTC, nguyenv commented
And also for reverting the libtiledb version in setup.py.

2024-03-21 15:55 UTC, merged