Wrap as_built function
TileDB-Inc/TileDB-Py pull request #1994
Opened 2024-06-18 21:09 UTC by kounelisagis

- Wraps `as_built` function.
- Adds test
- Fixes disable_stats typo

The function was implemented with an optional argument `as_string=False`.
This is because it is easier for the user to use a dictionary structure rather than a string. When the argument is set to `True`, the function returns output identical to the C API.

2024-06-20 12:23 UTC, ihnorton requested changes

2024-06-20 12:23 UTC, ihnorton commented on tiledb/highlevel.py
> +def as_built(as_string=False):
```suggestion
def as_built(return_json_string=False):
```

2024-06-20 12:55 UTC, kounelisagis commented
@ihnorton FYI I checked what `json.loads()` returns and it's a `<class 'dict'>` as intended.

2024-07-05 12:20 UTC, ihnorton approved these changes

2024-07-05 12:20 UTC, merged