Addition of `array_schema_name` Getter to Fragment Info API; Addition of `create_array_from_fragments`
TileDB-Inc/TileDB-Py pull request #777
Opened 2021-11-12 22:48 UTC by nguyenv

2021-11-12 22:53 UTC, nguyenv commented
I rebased this branch with the MBR branch to make it easier to merge everything into `dev` in the future, so there are "extra" commits.

2021-11-13 03:29 UTC, ihnorton requested changes

2021-11-13 03:29 UTC, ihnorton commented on tiledb/highlevel.py
> +                vfs.create_dir(os.path.join(dst_uri, "__schema"))
I think this needs to be conditional on whether the target exists. There could be multiple fragments referring to the same schema file, and I'm not sure if this `create_dir` will error out if the target already exists.

2021-11-13 03:29 UTC, ihnorton commented on tiledb/highlevel.py
> +                vfs.create_dir(os.path.join(dst_uri, "__schema"))
and the copy below too

2021-11-13 03:29 UTC, ihnorton commented
Two things for testing in follow up:

- use schema evolution to create multiple schema versions, along with corresponding writes at those versions. Test that `create_array_from_fragments` works correctly.
- we should also test creation in the presence of old style schema (or error out). one way to do this is to create an array with older tiledb-py version, then evolve it with a newer version, then test `create_array_from_fragments` (the old array can be stored as bytes inline in the test file, tar -> base64 encode; there are several existing compatibility test arrays like this)

2021-11-15 18:33 UTC, ihnorton requested changes
A couple change requests:
-  bug inline w/ schema copy
- error out if the target directory exists (currently does not error until the fragment copy step)

For follow up:
- would be nice to eventually support half-open intervals, eg `(start,None)`, currently that's a little bit fiddly (have to manually check/specify the fragment timestamps on both sides)

2021-11-15 18:33 UTC, ihnorton commented on tiledb/highlevel.py
> +        schema_name = fragment_info.array_schema_name[0]
Need to use `frag.array_schema_name`. Currently this is only copying the first array schema version, so the array is corrupted after copy.

2021-11-15 20:06 UTC, ihnorton commented on tiledb/highlevel.py
> +            "This array contains a mix of old and new style schemas"
Please clarify - "cannot copy fragments"

2021-11-15 20:43 UTC, ihnorton approved these changes
💯

2021-11-15 21:33 UTC, merged