[Merge in 0.13.0] Deprecate Partial Vacuuming
TileDB-Inc/TileDB-Py pull request #930
Opened 2022-02-25 17:24 UTC by nguyenv

2022-02-25 17:27 UTC, nguyenv commented on HISTORY.md
> +# TileDB-Py 0.12.4 Release Notes
Need to see where I messed up the README here...

2022-02-28 15:19 UTC, ihnorton requested changes
IIUC, this change was implemented in core by https://github.com/TileDB-Inc/TileDB/pull/2909

That PR will not be backported, so this functionality will still be available in 0.13 / libtiledb 2.7. So I think we should keep the functionality in place with the deprecation warning (it looks like this PR replaces the functionality with a warning?)

Also needs rebase.

2022-02-28 15:19 UTC, ihnorton commented on HISTORY.md
> +* Deprecate partial vacuuming []()
^ reminder

2022-03-02 03:41 UTC, ihnorton approved these changes

2022-03-02 14:21 UTC, merged